# Generated by Django 2.1.2 on 2018-11-06 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('enrolled_at', models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 6, 15, 20, 29, 755531))),
                ('gpa', models.IntegerField()),
            ],
        ),
    ]
